# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('migration_run', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='migration_run',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='migration_run.MigrationRun'),
            preserve_default=False,
        ),
    ]
