# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_source_migration_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='migration_run',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='migration_run.MigrationRun'),
        ),
    ]
