language: python
services: postgresql
python:
  - "3.6"
install:
  - pip install -r requirements/testing.txt
  - mv secrets.template.json secrets.json
script:
  - coverage run manage.py test
#after_success: coveralls