language: python
addons:
  postgresql: "9.4"
python:
  - "3.6"
install:
  - pip install -r requirements/testing.txt
before_script:
  - mv secrets.template.json secrets.json
  - psql -c 'create database goto_cloud;' -U postgres
script:
  - coverage run manage.py test
after_success:
  - coveralls