# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('os', models.CharField(default='Linux', max_length=255)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(max_length=512)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('password', models.CharField(blank=True, max_length=512, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('private_key_file_path', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
