# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 12:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_host', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotehost',
            name='system_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
