# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 11:51
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remote_host', '0002_remotehost_system_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotehost',
            name='cloud_metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
